class Demodata {
  constructor(name) {
    this.name = name;
  }
  data = {
    workpermit: [
      {
        id: 1,
        work_number: 'NMOD-02119/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายสมควร กระจ่าง',
        work_type: 'Hot Work',
        locatoin: 'GSP2',
        date_time_start: '1/4/2022  4:05:51',
        date_time_end: '1/5/2022  4:06:51',
        status_work: 'open',
      },
      {
        id: 2,
        work_number: 'NMOD-02120/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายสมควร กระจ่าง',
        work_type: 'Confined Space',
        locatoin: 'GSP1',
        date_time_start: '1/4/2022  4:00:00',
        date_time_end: '1/5/2022  4:00:00',
        status_work: 'open',
      },
      {
        id: 3,
        work_number: 'NMOD-02121/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายสมควร กระจ่าง',
        work_type: 'Excavation work',
        locatoin: 'GSP3',
        date_time_start: '20/4/2022  5:00:00',
        date_time_end: '20/5/2022  5:00:00',
        status_work: 'open',
      },
      {
        id: 4,
        work_number: 'NMOD-02122/64',
        name: 'นายสมชาย ใจมั่น',
        licensor: 'นางกิติยา วรกุญ',
        supervisor: 'นายภาณุวัฒน์ อารีย์',
        work_type: 'COLD WORK',
        locatoin: 'ESP',
        date_time_start: '10/2/2022  11:00:00',
        date_time_end: '10/3/2022  11:00:00',
        status_work: 'close',
      },
      {
        id: 5,
        work_number: 'NMOD-02123/64',
        name: 'นายสมชาย ใจมั่น',
        licensor: 'นางกิติยา วรกุญ',
        supervisor: 'นายภาณุวัฒน์ อารีย์',
        work_type: 'CONFINED SPACE ENTRY',
        locatoin: 'CWWTP',
        date_time_start: '1/4/2022  15:00:00',
        date_time_end: '1/5/2022  15:00:00',
        status_work: 'open',
      },
      {
        id: 6,
        work_number: 'NMOD-02124/64',
        name: 'นายสมชาย ใจมั่น',
        licensor: 'นางกิติยา วรกุญ',
        supervisor: 'นายภาณุวัฒน์ อารีย์',
        work_type: 'RADIO ISOTOPES',
        locatoin: 'Tank Farm',
        date_time_start: '1/1/2022  12:00:00',
        date_time_end: '1/2/2022  12:00:00',
        status_work: 'close',
      },
      {
        id: 7,
        work_number: 'NMOD-02125/64',
        name: 'นายอดิศักดิ์ แก้วมณี',
        licensor: 'นายอนุรักษ์ พัฒน์พงษ์',
        supervisor: 'นางสาววารี รัศมี',
        work_type: 'EXCAVATION',
        locatoin: 'GPPP',
        date_time_start: '11/4/2022  9:00:00',
        date_time_end: '11/5/2022  9:00:00',
        status_work: 'open',
      },
      {
        id: 8,
        work_number: 'NMOD-02126/64',
        name: 'นายอดิศักดิ์ แก้วมณี',
        licensor: 'นายอนุรักษ์ พัฒน์พงษ์',
        supervisor: 'นางสาววารี รัศมี',
        work_type: 'ELECTRICAL',
        locatoin: 'GSP5',
        date_time_start: '9/4/2022  8:00:00',
        date_time_end: '9/5/2022  8:00:00',
        status_work: 'open',
      },
      {
        id: 9,
        work_number: 'NMOD-02127/64',
        name: 'นายอดิศักดิ์ แก้วมณี',
        licensor: 'นายอนุรักษ์ พัฒน์พงษ์',
        supervisor: 'นางสาววารี รัศมี',
        work_type: 'SCAFFOLDING',
        locatoin: 'GSP6',
        date_time_start: '19/5/2022  10:00:00',
        date_time_end: '19/6/2022  10:00:00',
        status_work: 'open',
      },
      {
        id: 10,
        work_number: 'NMOD-02128/64',
        name: 'นายอดิศักดิ์ แก้วมณี',
        licensor: 'นายอนุรักษ์ พัฒน์พงษ์',
        supervisor: 'นางสาววารี รัศมี',
        work_type: 'MOBILE CRANE',
        locatoin: 'ESP',
        date_time_start: '5/5/2022  14:00:00',
        date_time_end: '5/6/2022  14:00:00',
        status_work: 'open',
      },
    ],
    vehicle: [
      {
        id: 1,
        work_number: 'NMOD-02131/64',
        name: 'นายกิติศักดิ์ มณีรัตน์',
        licensor: 'นายอัศวิน แก้วโชติ',
        supervisor: 'นางวิชุดา ภักดีกัลยา',
        car_registration: 'กง- 2000 ระยอง',
        car_type: 'รถยก',
        locatoin: 'GSP1',
        date_time_start: '1/4/2022  4:00:50',
        date_time_end: '1/5/2022  4:00:50',
        status_work: 'open',
        status_warnning: 'ไม่ได้รับอนุญาตให้เข้าพื้นที่',
      },
      {
        id: 2,
        work_number: 'NMOD-02132/64',
        name: 'นายกิติศักดิ์ มณีรัตน์',
        licensor: 'นายอัศวิน แก้วโชติ',
        supervisor: 'นางวิชุดา ภักดีกัลยา',
        car_registration: 'กม- 2132 ระยอง',
        car_type: 'รถเครน',
        locatoin: 'GSP2',
        date_time_start: '15/4/2022  15:00:00',
        date_time_end: '15/5/2022  15:00:00',
        status_work: 'open',
        status_warnning: 'ขับออกนอกเส้นทาง',
      },
      {
        id: 3,
        work_number: 'NMOD-02133/64',
        name: 'นายกิติศักดิ์ มณีรัตน์',
        licensor: 'นายอัศวิน แก้วโชติ',
        supervisor: 'นางวิชุดา ภักดีกัลยา',
        car_registration: 'กม- 5051 ระยอง',
        car_type: 'รถเฮี้ยบ',
        locatoin: 'GSP3',
        date_time_start: '1/2/2022  12:30:00',
        date_time_end: '1/3/2022  12:30:00',
        status_work: 'close',
        status_warnning: 'ไม่ได้รับอนุญาตให้เข้าพื้นที่',
      },
      {
        id: 4,
        work_number: 'NMOD-02134/64',
        name: 'นายณัฐกรณ์ อมรศิลป์',
        licensor: 'นายอนุรักษ์ อมรมงคล',
        supervisor: 'นายวิทยเดช เลิศชัย',
        car_registration: 'กก- 5789 ระยอง',
        car_type: 'รถยนต์',
        locatoin: 'ESP',
        date_time_start: '10/4/2022  10:30:00',
        date_time_end: '10/5/2022  10:30:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 5,
        work_number: 'NMOD-02135/64',
        name: 'นายณัฐกรณ์ อมรศิลป์',
        licensor: 'นายอนุรักษ์ อมรมงคล',
        supervisor: 'นายวิทยเดช เลิศชัย',
        car_registration: 'กย- 1265 ระยอง',
        car_type: 'รถบรรทุก',
        locatoin: 'CWWTP',
        date_time_start: '14/4/2022  10:40:00',
        date_time_end: '14/5/5/2022  10:40:00',
        status_work: 'open',
        status_warnning: 'จอดในจุดที่ไม่ได้กำหนด',
      },
      {
        id: 6,
        work_number: 'NMOD-02136/64',
        name: 'นายณัฐกรณ์ อมรศิลป์',
        licensor: 'นายอนุรักษ์ อมรมงคล',
        supervisor: 'นายวิทยเดช เลิศชัย',
        car_registration: 'ยย- 0001 ระยอง',
        car_type: 'รถเครน',
        locatoin: 'Tank Farm',
        date_time_start: '23/4/2022  10:00:00',
        date_time_end: '23/5/5/2022  10:00:00',
        status_work: 'open',
        status_warnning: 'ขับออกนอกพื้นที่ควบคุม',
      },
      {
        id: 7,
        work_number: 'NMOD-02137/64',
        name: 'นายวีรยุทธ แสงสุวรรณา',
        licensor: 'นายอนุพงษ์  ปิ่นทอง',
        supervisor: 'นางอรนุช พิพัฒน์ทรัพย์',
        car_registration: 'กก- 0231 ระยอง',
        car_type: 'รถยนต์',
        locatoin: 'GPPP',
        date_time_start: '26/4/2022  8:00:00',
        date_time_end: '26/5/5/2022  8:00:00',
        status_work: 'open',
        status_warnning: 'ใช้ความเร็วเกินกำหนด',
      },
      {
        id: 8,
        work_number: 'NMOD-02138/64',
        name: 'นายวีรยุทธ แสงสุวรรณา',
        licensor: 'นายอนุพงษ์  ปิ่นทอง',
        supervisor: 'นางอรนุช พิพัฒน์ทรัพย์',
        car_registration: 'กก- 1567 ระยอง',
        car_type: 'รถเฮี้ยบ',
        locatoin: 'GPPP',
        date_time_start: '28/4/2022  16:30:00',
        date_time_end: '28/5/5/2022  16:30:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 9,
        work_number: 'NMOD-02139/64',
        name: 'นายวีรยุทธ แสงสุวรรณา',
        licensor: 'นายอนุพงษ์  ปิ่นทอง',
        supervisor: 'นางอรนุช พิพัฒน์ทรัพย์',
        car_registration: 'รล- 3337 ระยอง',
        car_type: 'รถบรรทุก',
        locatoin: 'GSP5',
        date_time_start: '29/4/2022  16:00:00',
        date_time_end: '29/5/5/2022  16:00:00',
        status_work: 'open',
        status_warnning: 'จอดในจุดที่ไม่ได้กำหนด',
      },
      {
        id: 10,
        work_number: 'NMOD-02140/64',
        name: 'นายอัครเดช มากมี',
        licensor: 'นายอติวัฒน์ พนมกร',
        supervisor: 'นายทวี โอภาส',
        car_registration: 'กก- 7745 ระยอง',
        car_type: 'รถยก',
        locatoin: 'GSP6',
        date_time_start: '30/4/2022  9:50:00',
        date_time_end: '30/5/5/2022  9:50:00',
        status_work: 'open',
        status_warnning: null,
      },
    ],
    equipment: [
      {
        id: 1,
        work_number: 'NMOD-02141/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายสมควร กระจ่าง',
        device_type: 'เครื่องจักรงานเจาะและตอก',
        locatoin: 'GSP1',
        expire_date: '1/3/2022',
        date_time_start: '1/2/2022  4:05:00',
        date_time_end: '1/3/2022  4:06:00',
        status_work: 'close',
        status_warnning: 'หมดอายุ',
      },
      {
        id: 2,
        work_number: 'NMOD-02142/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายสมควร กระจ่าง',
        device_type: 'เครื่องจักรงานผสมวัสดุ',
        locatoin: 'GSP2',
        expire_date: '15/5/2022',
        date_time_start: '15/4/2022  14:30:00',
        date_time_end: '15/5/2022  14:30:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 3,
        work_number: 'NMOD-02143/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายสมควร กระจ่าง',
        device_type: 'เครื่องจักรงานผสมวัสดุ',
        locatoin: 'GSP3',
        expire_date: '30/4/2022',
        date_time_start: '30/3/2022  11:30:00',
        date_time_end: '30/4/2022  11:30:00',
        status_work: 'open',
        status_warnning: 'ใกล้หมดอายุ',
      },
      {
        id: 4,
        work_number: 'NMOD-02144/64',
        name: 'นายสุรศักดิ์ โชครักษา',
        licensor: 'นางสาวปรียานุช อ่อนโยน',
        supervisor: 'นายมานะ พัชรกุล',
        device_type: 'เครื่องจักรกลงานย้ายวัสดุแข็งขนาดใหญ่',
        locatoin: 'ESP',
        expire_date: '28/5/2022',
        date_time_start: '28/4/2022  11:00:00',
        date_time_end: '28/5/2022  11:00:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 5,
        work_number: 'NMOD-02145/64',
        name: 'นายสุรศักดิ์ โชครักษา',
        licensor: 'นางสาวปรียานุช อ่อนโยน',
        supervisor: 'นายมานะ พัชรกุล',
        device_type: 'เครื่องแยกสถานะก๊าซ',
        locatoin: 'CWWTP',
        expire_date: '15/5/2022',
        date_time_start: '15/4/2022  9:00:00',
        date_time_end: '15/5/2022  9:00:00',
        status_work: 'open',
        status_warnning: 'อุปกรณ์เสี่ยง',
      },
      {
        id: 6,
        work_number: 'NMOD-02146/64',
        name: 'นายสุรศักดิ์ โชครักษา',
        licensor: 'นางสาวปรียานุช อ่อนโยน',
        supervisor: 'นายมานะ พัชรกุล',
        device_type: 'แท่นขุดเจาะก๊าซ',
        locatoin: 'Tank Farm',
        expire_date: '1/5/2022',
        date_time_start: '1/4/2022  9:30:00',
        date_time_end: '1/5/2022  9:30:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 7,
        work_number: 'NMOD-02147/64',
        name: 'นายวัชรากร อาจหาญ',
        licensor: 'นายกิตติศักดิ์ มโนไพศาล',
        supervisor: 'นายวิทยการ ทิพยการ',
        device_type: 'เครื่องแยกสถานะก๊าซ',
        locatoin: 'GPPP',
        expire_date: '10/5/2022',
        date_time_start: '10/4/2022  11:30:00',
        date_time_end: '10/5/2022  11:30:00',
        status_work: 'open',
        status_warnning: 'อุปกรณ์เสี่ยง',
      },
      {
        id: 8,
        work_number: 'NMOD-02148/64',
        name: 'นายวัชรากร อาจหาญ',
        licensor: 'นายกิตติศักดิ์ มโนไพศาล',
        supervisor: 'นายวิทยการ ทิพยการ',
        device_type: 'เครื่องจักรกลงานย้ายวัสดุแข็งขนาดใหญ่',
        locatoin: 'GSP5',
        expire_date: '18/5/2022',
        date_time_start: '18/4/2022  11:00:00',
        date_time_end: '18/5/2022  11:00:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 9,
        work_number: 'NMOD-02149/64',
        name: 'นายวัชรากร อาจหาญ',
        licensor: 'นายกิตติศักดิ์ มโนไพศาล',
        supervisor: 'นายวิทยการ ทิพยการ',
        device_type: 'เครื่องจักรกลงานย้ายวัสดุแข็งขนาดใหญ่',
        locatoin: 'GSP6',
        expire_date: '28/4/2022',
        date_time_start: '28/3/2022  8:00:00',
        date_time_end: '28/4/2022  8:00:00',
        status_work: 'open',
        status_warnning: 'ใกล้หมดอายุ',
      },
      {
        id: 10,
        work_number: 'NMOD-02150/64',
        name: 'นายวัชรากร อาจหาญ',
        licensor: 'นายกิตติศักดิ์ มโนไพศาล',
        supervisor: 'นายวิทยการ ทิพยการ',
        device_type: 'เครื่องจักรงานเจาะและตอก',
        locatoin: 'GSP6',
        expire_date: '23/5/2022',
        date_time_start: '23/4/2022  18:00:00',
        date_time_end: '23/5/2022  18:00:00',
        status_work: 'open',
        status_warnning: null,
      },
    ],
    access_control: [
      {
        id: 1,
        contractor_name: 'นายศักดิ์ชัย จำเริญรักษ์',
        people_type: 'ผู้รับเหมา',
        supervisor: 'นายมงคล นาราธรณี',
        locatoin_scan: 'GPPP',
        time_scan: '9:00:00',
        date_time_start: '1/4/2022  14:00:00',
        date_time_end: '1/5/2022  14:00:00',
        exchange_card_in: '2/4/2022  09:00:00',
        exchange_card_out: '2/4/2022  17:00:00',
      },
      {
        id: 2,
        contractor_name: 'นายราชันต์ พันธ์ชาติ',
        people_type: 'ผู้รับเหมา',
        supervisor: 'นายมงคล นาราธรณี',
        locatoin_scan: 'Tank Farm',
        time_scan: '8:30:00',
        date_time_start: '1/4/2022  14:00:00',
        date_time_end: '1/5/2022  14:00:00',
        exchange_card_in: '2/4/2022  08:30:00',
        exchange_card_out: '2/4/2022  17:00:00',
      },
      {
        id: 3,
        contractor_name: 'นายวิริยะ ภักดี',
        people_type: 'ผู้รับเหมา',
        supervisor: 'นายมงคล นาราธรณี',
        locatoin_scan: 'ESP',
        time_scan: '9:30:00',
        date_time_start: '3/4/2022  15:00:00',
        date_time_end: '3/5/2022  15:00:00',
        exchange_card_in: '2/4/2022  09:30:00',
        exchange_card_out: '2/4/2022  18:00:00',
      },
      {
        id: 4,
        contractor_name: 'นายมานะ องอาจกุล',
        people_type: 'เจ้าหน้าที่รักษาความปลอดภัย',
        supervisor: 'นายพัชระ อมรเวช',
        locatoin_scan: 'GSP2',
        time_scan: '9:00:00',
        date_time_start: '5/4/2022  11:00:00',
        date_time_end: '5/5/2022  11:00:00',
        exchange_card_in: '2/4/2022  09:00:00',
        exchange_card_out: '2/4/2022  18:00:00',
      },
      {
        id: 5,
        contractor_name: 'นายอนุกุล บุตรพรหม',
        people_type: 'เจ้าหน้าที่รักษาความปลอดภัย',
        supervisor: 'นายพัชระ อมรเวช',
        locatoin_scan: 'GSP1',
        time_scan: '9:30:00',
        date_time_start: '8/4/2022  11:00:00',
        date_time_end: '8/5/2022  11:00:00',
        exchange_card_in: '2/4/2022  09:30:00',
        exchange_card_out: '2/4/2022  18:30:00',
      },
      {
        id: 6,
        contractor_name: 'นางสาววิภาพร แก้วหอม',
        people_type: 'หน่วยงาน ปภ.ผยก.',
        supervisor: 'นายพัชระ อมรเวช',
        locatoin_scan: 'GSP5',
        time_scan: '10:00:00',
        date_time_start: '15/4/2022  15:00:00',
        date_time_end: '15/5/2022  15:00:00',
        exchange_card_in: '2/4/2022  10:00:00',
        exchange_card_out: '2/4/2022  18:00:00',
      },
      {
        id: 7,
        contractor_name: 'นายวัชรกร มณีแสง',
        people_type: 'หน่วยงาน ปภ.ผยก.',
        supervisor: 'นายพัชระ อมรเวช',
        locatoin_scan: 'GSP1',
        time_scan: '10:30:00',
        date_time_start: '18/4/2022  15:00:00',
        date_time_end: '18/5/2022  15:00:00',
        exchange_card_in: '2/4/2022  10:30:00',
        exchange_card_out: '2/4/2022  18:30:00',
      },
      {
        id: 8,
        contractor_name: 'นายกรกวี กรกรรณ',
        people_type: 'ผู้รับเหมา',
        supervisor: 'นายรัชกาล กาลพรม',
        locatoin_scan: 'GSP1',
        time_scan: '10:00:00',
        date_time_start: '20/4/2022  10:00:00',
        date_time_end: '20/5/2022  10:00:00',
        exchange_card_in: '2/4/2022  10:00:00',
        exchange_card_out: '2/4/2022  19:00:00',
      },
      {
        id: 9,
        contractor_name: 'นายกรกวี กรกรรณ',
        people_type: 'ผู้รับเหมา',
        supervisor: 'นายรัชกาล กาลพรม',
        locatoin_scan: 'GSP3',
        time_scan: '10:00:00',
        date_time_start: '23/4/2022  10:00:00',
        date_time_end: '23/5/2022  10:00:00',
        exchange_card_in: '2/4/2022  10:00:00',
        exchange_card_out: '2/4/2022  19:00:00',
      },
      {
        id: 10,
        contractor_name: 'นายนิกร เจริญทรัพย์',
        people_type: 'ผู้ควบคุมงาน ปตท.',
        supervisor: 'นายรัชกาล กาลพรม',
        locatoin_scan: 'GSP2',
        time_scan: '08:30:00',
        date_time_start: '25/4/2022  10:00:00',
        date_time_end: '25/5/2022  10:00:00',
        exchange_card_in: '2/4/2022  08:30:00',
        exchange_card_out: '2/4/2022  17:30:00',
      },
    ],
    people_tracking: [
      {
        id: 1,
        work_number: 'NMOD-02161/64',
        name: 'นายโอภาส เพชรงาม',
        licensor: 'นางจุฑามาศ อรุโณทัย',
        supervisor: 'นายปวีร์ สืบสกุล',
        people_type: 'ผู้รับเหมา',
        locatoin: 'Tank Farm',
        date_time_start: '1/4/2022  4:30:00',
        date_time_end: '1/5/2022  4:30:00',
        status_work: 'open',
        status_warnning: 'นิ่งเกิน 30 นาที',
      },
      {
        id: 2,
        work_number: 'NMOD-02162/64',
        name: 'นายไพศาล สวัสดิโชติ',
        licensor: 'นางจุฑามาศ อรุโณทัย',
        supervisor: 'นายปวีร์ สืบสกุล',
        people_type: 'ผู้รับเหมา',
        locatoin: 'ESP',
        date_time_start: '10/4/2022  8:30:00',
        date_time_end: '10/5/2022  8:30:00',
        status_work: 'open',
        status_warnning: 'ออกนอกพื้นที่',
      },
      {
        id: 3,
        work_number: 'NMOD-02163/64',
        name: 'นายชาติชาย ใจรัก',
        licensor: 'นางจุฑามาศ อรุโณทัย',
        supervisor: 'นายปวีร์ สืบสกุล',
        people_type: 'เจ้าหน้าที่รักษาความปลอดภัย',
        locatoin: 'GSP1',
        date_time_start: '11/4/2022  8:30:00',
        date_time_end: '11/5/2022  8:30:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 4,
        work_number: 'NMOD-02164/64',
        name: 'นายอดิศร จักรวาล',
        licensor: 'นายประดิษฐ์ วิเศษ',
        supervisor: 'นายอดิศร จักรวาล',
        people_type: 'ผู้ควบคุมงาน',
        locatoin: 'GSP2',
        date_time_start: '12/4/2022  8:00:00',
        date_time_end: '12/5/2022  8:00:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 5,
        work_number: 'NMOD-02165/64',
        name: 'นายสิทธิชัย ไกลราช',
        licensor: 'นายประดิษฐ์ วิเศษ',
        supervisor: 'นายอดิศร จักรวาล',
        people_type: 'ผู้รับเหมา',
        locatoin: 'GSP3',
        date_time_start: '12/3/2022  8:00:00',
        date_time_end: '12/4/2022  8:00:00',
        status_work: 'close',
        status_warnning: 'work หมดอายุ',
      },
      {
        id: 6,
        work_number: 'NMOD-02166/64',
        name: 'นายเพชรัตน์ เพชรแพรว',
        licensor: 'นายประดิษฐ์ วิเศษ',
        supervisor: 'นายอดิศร จักรวาล',
        people_type: 'ผู้รับเหมา',
        locatoin: 'GSP5',
        date_time_start: '12/4/2022  10:00:00',
        date_time_end: '12/5/2022  10:00:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 7,
        work_number: 'NMOD-02167/64',
        name: 'นางสาวเกตุมณี ไพศาลกุล',
        licensor: 'นายอนิรุต วุฒิกร',
        supervisor: 'นายมงคล นาราธรณี',
        people_type: 'เจ้าหน้าที่รักษาความปลอดภัย',
        locatoin: 'CWWTP',
        date_time_start: '18/4/2022  8:40:00',
        date_time_end: '18/5/2022  8:40:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 8,
        work_number: 'NMOD-02168/64',
        name: 'นายปติมากร สุรัตน์',
        licensor: 'นายอนิรุต วุฒิกร',
        supervisor: 'นายมงคล นาราธรณี',
        people_type: 'ผู้รับเหมา',
        locatoin: 'GSP3',
        date_time_start: '18/4/2022  10:30:00',
        date_time_end: '18/5/2022  10:30:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 9,
        work_number: 'NMOD-02169/64',
        name: 'นายมงคล นาราธรณี',
        licensor: 'นายอนิรุต วุฒิกร',
        supervisor: 'นายมงคล นาราธรณี',
        people_type: 'ผู้ควบคุมงาน',
        locatoin: 'GSP3',
        date_time_start: '20/4/2022  13:30:00',
        date_time_end: '20/5/2022  13:30:00',
        status_work: 'open',
        status_warnning: null,
      },
      {
        id: 10,
        work_number: 'NMOD-02170/64',
        name: 'นายวิวัฒน์ ทองดี',
        licensor: 'นายอนิรุต วุฒิกร',
        supervisor: 'นายมงคล นาราธรณี',
        people_type: 'ผู้รับเหมา',
        locatoin: 'GSP6',
        date_time_start: '22/4/2022  14:00:00',
        date_time_end: '22/5/2022  14:00:00',
        status_work: 'open',
        status_warnning: null,
      },
    ],
    scaffolding: [
      {
        id: 1,
        work_number: 'NMOD-02151/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายณภัทร อมรราช',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'GSP6',
        expire_date: '29/4/2022',
        date_time_start: '29/3/2022  14:05:00',
        date_time_end: '29/4/2022  14:05:00',
        scaffolding_type: 'นั่งร้านแบบเสาเรียงคู่',
        status_warnning: 'นั่งร้านใกล้หมดอายุ',
      },
      {
        id: 2,
        work_number: 'NMOD-02152/64',
        name: 'นายศักดิ์ชัย จำเริญรักษ์',
        licensor: 'นางพัชรา พิชญศุภากิจ',
        supervisor: 'นายณภัทร อมรราช',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'GSP5',
        expire_date: '30/4/2022',
        date_time_start: '30/3/2022  10:30:00',
        date_time_end: '30/4/2022  10:30:00',
        scaffolding_type: 'นั่งร้านแบบเสาเรียงเดี่ยว',
        status_warnning: 'นั่งร้านใกล้หมดอายุ',
      },
      {
        id: 3,
        work_number: 'NMOD-02153/64',
        name: 'นายอติภัทร หินแก้ว',
        licensor: 'นายอนุกุล สุรีวงศ์',
        supervisor: 'นางสุชาวดี นีรกุล',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'ESP',
        expire_date: '25/4/2022',
        date_time_start: '25/3/2022  8:30:00',
        date_time_end: '25/4/2022  8:30:00',
        scaffolding_type: 'นั่งร้านแบบแขวนยื่น',
        status_warnning: 'นั่งร้านหมดอายุ',
      },
      {
        id: 4,
        work_number: 'NMOD-02154/64',
        name: 'นายอติภัทร หินแก้ว',
        licensor: 'นายอนุกุล สุรีวงศ์',
        supervisor: 'นางสุชาวดี นีรกุล',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'CWWTP',
        expire_date: '20/5/2022',
        date_time_start: '20/4/2022  8:00:00',
        date_time_end: '20/5/2022  8:00:00',
        scaffolding_type: 'นั่งร้านแบบเคลื่อนที่ได้',
        status_warnning: null,
      },
      {
        id: 5,
        work_number: 'NMOD-02155/64',
        name: 'นายอติภัทร หินแก้ว',
        licensor: 'นายอนุกุล สุรีวงศ์',
        supervisor: 'นางสุชาวดี นีรกุล',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'Tank Farm',
        expire_date: '22/5/2022',
        date_time_start: '22/4/2022  9:00:00',
        date_time_end: '22/5/2022  9:00:00',
        scaffolding_type: 'นั่งร้านแบบเคลื่อนที่ได้',
        status_warnning: null,
      },
      {
        id: 6,
        work_number: 'NMOD-02156/64',
        name: 'นายอรงกรณ์ นามธรรม',
        licensor: 'นางสาวมณีนุช อุ่นใจ',
        supervisor: 'นายวิรัช แก้วมณี',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'GSP1',
        expire_date: '22/4/2022',
        date_time_start: '22/3/2022  10:00:00',
        date_time_end: '22/4/2022  10:00:00',
        scaffolding_type: 'นั่งร้านแบบใช้เหล็กท่อประกอบ',
        status_warnning: 'นั่งร้านหมดอายุ',
      },
      {
        id: 7,
        work_number: 'NMOD-02157/64',
        name: 'นายอรงกรณ์ นามธรรม',
        licensor: 'นางสาวมณีนุช อุ่นใจ',
        supervisor: 'นายวิรัช แก้วมณี',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'GSP3',
        expire_date: '19/5/2022',
        date_time_start: '19/4/2022  9:30:00',
        date_time_end: '19/5/2022  9:30:00',
        scaffolding_type: 'นั่งร้านแบบใช้เหล็กท่อประกอบ',
        status_warnning: null,
      },
      {
        id: 8,
        work_number: 'NMOD-02158/64',
        name: 'นายอรงกรณ์ นามธรรม',
        licensor: 'นางสาวมณีนุช อุ่นใจ',
        supervisor: 'นายวิรัช แก้วมณี',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'GSP2',
        expire_date: '15/5/2022',
        date_time_start: '15/4/2022  11:30:00',
        date_time_end: '15/5/2022  11:30:00',
        scaffolding_type: 'นั่งร้านแบบเสาเรียงคู่',
        status_warnning: null,
      },
      {
        id: 9,
        work_number: 'NMOD-02159/64',
        name: 'นายโอภาส เพชรงาม',
        licensor: 'นางจุฑามาศ อรุโณทัย',
        supervisor: 'นายปวีร์ สืบสกุล',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'Tank Farm',
        expire_date: '10/5/2022',
        date_time_start: '10/4/2022  14:40:00',
        date_time_end: '10/5/2022  14:40:00',
        scaffolding_type: 'นั่งร้านแบบเสาเรียงเดี่ยว',
        status_warnning: null,
      },
      {
        id: 10,
        work_number: 'NMOD-02160/64',
        name: 'นายโอภาส เพชรงาม',
        licensor: 'นางจุฑามาศ อรุโณทัย',
        supervisor: 'นายปวีร์ สืบสกุล',
        workmit_type: 'ใบอนุญาตติดตั้ง/รื้อถอนนั่งร้าน',
        locatoin: 'CWWTP',
        expire_date: '12/5/2022',
        date_time_start: '12/4/2022  17:30:00',
        date_time_end: '12/5/2022  17:30:00',
        scaffolding_type: 'นั่งร้านแบบแขวนยื่น',
        status_warnning: null,
      },
    ],
  };

  getRandomLocation = function (latitude, longitude, radiusInMeters) {
    var getRandomCoordinates = function (radius, uniform) {
      // Generate two random numbers
      var a = Math.random(),
        b = Math.random();

      // Flip for more uniformity.
      if (uniform) {
        if (b < a) {
          var c = b;
          b = a;
          a = c;
        }
      }

      // It's all triangles.
      return [
        b * radius * Math.cos((2 * Math.PI * a) / b),
        b * radius * Math.sin((2 * Math.PI * a) / b),
      ];
    };

    var randomCoordinates = getRandomCoordinates(radiusInMeters, true);

    // Earths radius in meters via WGS 84 model.
    var earth = 6378137;

    // Offsets in meters.
    var northOffset = randomCoordinates[0],
      eastOffset = randomCoordinates[1];

    // Offset coordinates in radians.
    var offsetLatitude = northOffset / earth,
      offsetLongitude =
        eastOffset / (earth * Math.cos(Math.PI * (latitude / 180)));

    // Offset position in decimal degrees.
    return {
      // ...randomProfile.profile(),
      latitude: latitude + offsetLatitude * (180 / Math.PI),
      longitude: longitude + offsetLongitude * (180 / Math.PI),
      // type: ["warning", "Open", "close"].random()
    };
  };

  getDemodata = async function () {
    try {
      let datanew = [];
      for (const key in this.data[this.name]) {
        // console.log('object :>> ', this.data[this.name][key])
        let latlng = await this.getRandomLocation(13.78288, 100.3229211, 100);
        datanew.push({
          ...this.data[this.name][key],
          ...latlng,
        });
      }

      return datanew;
    } catch (error) {
      console.error('namecontrustornot math');
    }
  };
}

export default Demodata;
